//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_ebuilder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public employee(employeeRegister emp)
        {
            this.EID = emp.EID;
            this.email = emp.email;
            this.fName = emp.fName;
            this.lName = emp.lName;
            this.dob = emp.dob;
            this.gender = emp.gender;
            this.homeNo = emp.homeNo;
            this.street = emp.street;
            this.city = emp.city;
            this.jobCategory = emp.jobCategory;
        }

        public employee()
        {
            this.attendances = new HashSet<attendance>();
            this.leavs = new HashSet<leav>();
            this.tasks = new HashSet<task>();
            this.duty_leave = new HashSet<duty_leave>();
            this.employee1 = new HashSet<employee>();
            this.employees = new HashSet<employee>();
            this.notifications = new HashSet<notification>();
            this.approvals = new HashSet<approval>();
        }

        public string EID { get; set; }
        public string password { get; set; }

        [Display(Name ="Email")]
        public string email { get; set; }
        public Nullable<bool> emailVerified { get; set; }
        public string activationCode { get; set; }

        [Display(Name ="Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime dob { get; set; }

        [Display(Name ="First Name")]
        public string fName { get; set; }

        [Display(Name ="Last Name")]
        public string lName { get; set; }

        [Display(Name ="Gender")]
        public string gender { get; set; }

        [Display(Name ="Home No.")]
        public string homeNo { get; set; }

        [Display(Name ="Street")]
        public string street { get; set; }

        [Display(Name ="City")]
        public string city { get; set; }

        [Display(Name ="Job Category")]
        public string jobCategory { get; set; }

        internal virtual ICollection<attendance> attendances { get; set; }
        internal virtual ICollection<leav> leavs { get; set; }
        internal virtual ICollection<task> tasks { get; set; }
        internal virtual ICollection<duty_leave> duty_leave { get; set; }
        internal virtual ICollection<employee> employee1 { get; set; }
        internal virtual ICollection<employee> employees { get; set; }
        internal virtual ICollection<notification> notifications { get; set; }
        internal virtual ICollection<approval> approvals { get; set; }
    }
}
