//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_ebuilder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class leave_type
    {
        public leave_type()
        {
            this.leavs = new HashSet<leav>();
        }

        [Required(ErrorMessage ="Required")]
        [Display(Name ="Job Category")]
        public string jobCategory { get; set; }

        [Required(ErrorMessage ="Required")]
        [Display(Name ="Leave Category")]
        public string leaveCategory { get; set; }

        [Required(ErrorMessage ="Required")]
        [Display(Name ="Max Allowed")]
        [Range(0,int.MaxValue,ErrorMessage ="Enter a valid number")]
        public int maxAllowed { get; set; }

        internal virtual ICollection<leav> leavs { get; set; }
    }
}
